[MySQL]
Login = "db_username"
Pass = "db_password"
DbName = "database_name"
IP = "127.0.0.1"
Port = "3306"
Protocol = "tcp"

[Redis]
Addr = "localhost:6379"
Pass = "lJKFQZGTmNQ1OSdXgJhfe/JMpuCXYgB"
Conn = 0
ExpireSeconds = 300

[Host]
Port = "8080"
Key = "cert/localhost.key"
Cert = "cert/localhost.crt"

HTTP = false

[SMTP]
MailVerify = "fortstudio8@gmail.com"
Password = "12345678"
Hostname = "smtp.gmail.com"
Port = 587